// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDDYSZevJvxAdGmyxNG6pYOjnWhaHQoy0',
    appId: '1:543286410612:web:2e1384f749ecc4278a0021',
    messagingSenderId: '543286410612',
    projectId: 'mushroommonitor-7cd37',
    authDomain: 'mushroommonitor-7cd37.firebaseapp.com',
    storageBucket: 'mushroommonitor-7cd37.firebasestorage.app',
    measurementId: 'G-JDQ41GHVXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2w39hixQkPpPsjiCIY9goEaGGxGYb51w',
    appId: '1:543286410612:android:2056e0feb30bc75f8a0021',
    messagingSenderId: '543286410612',
    projectId: 'mushroommonitor-7cd37',
    storageBucket: 'mushroommonitor-7cd37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0-PLn0y1_h6Qx8shoXNiqTNPu3km61dM',
    appId: '1:543286410612:ios:254290e1f5cc42ea8a0021',
    messagingSenderId: '543286410612',
    projectId: 'mushroommonitor-7cd37',
    storageBucket: 'mushroommonitor-7cd37.firebasestorage.app',
    iosBundleId: 'com.example.mushroomMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0-PLn0y1_h6Qx8shoXNiqTNPu3km61dM',
    appId: '1:543286410612:ios:254290e1f5cc42ea8a0021',
    messagingSenderId: '543286410612',
    projectId: 'mushroommonitor-7cd37',
    storageBucket: 'mushroommonitor-7cd37.firebasestorage.app',
    iosBundleId: 'com.example.mushroomMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDDYSZevJvxAdGmyxNG6pYOjnWhaHQoy0',
    appId: '1:543286410612:web:990a2022a10a9e7f8a0021',
    messagingSenderId: '543286410612',
    projectId: 'mushroommonitor-7cd37',
    authDomain: 'mushroommonitor-7cd37.firebaseapp.com',
    storageBucket: 'mushroommonitor-7cd37.firebasestorage.app',
    measurementId: 'G-548RSPVTFG',
  );
}
